export type ProductionMenuFixtureItem = {
  name: string;
  mealPeriods: Array<"breakfast" | "lunch" | "dinner" | "allday">;
  sortOrder: number;
  svgKey: string;
  priceOptions: Array<{
    label: string | null;
    amountMinor: number;
    currency: string;
    sortOrder: number;
  }>;
};

/**
 * Public menu snapshot from the production canteen dataset (2026-07-30).
 * Production UUIDs and all user-generated data are intentionally excluded.
 */
export const PRODUCTION_MENU_FIXTURE: ProductionMenuFixtureItem[] = [
  {
    name: "叉燒包（1個）",
    mealPeriods: ["breakfast"],
    sortOrder: 0,
    svgKey: "default",
    priceOptions: [
      { label: null, amountMinor: 600, currency: "HKD", sortOrder: 0 },
    ],
  },
  {
    name: "菜肉包（1個）",
    mealPeriods: ["breakfast"],
    sortOrder: 1,
    svgKey: "default",
    priceOptions: [
      { label: null, amountMinor: 600, currency: "HKD", sortOrder: 0 },
    ],
  },
  {
    name: "香菇雞肉包（1個）",
    mealPeriods: ["breakfast"],
    sortOrder: 2,
    svgKey: "default",
    priceOptions: [
      { label: null, amountMinor: 600, currency: "HKD", sortOrder: 0 },
    ],
  },
  {
    name: "魚肉燒賣（6粒）",
    mealPeriods: ["breakfast"],
    sortOrder: 3,
    svgKey: "default",
    priceOptions: [
      { label: null, amountMinor: 1200, currency: "HKD", sortOrder: 0 },
    ],
  },
  {
    name: "腸粉（4條／素）",
    mealPeriods: ["breakfast"],
    sortOrder: 4,
    svgKey: "noodle",
    priceOptions: [
      { label: null, amountMinor: 1400, currency: "HKD", sortOrder: 0 },
    ],
  },
  {
    name: "雙蛋公仔麵（素）",
    mealPeriods: ["breakfast"],
    sortOrder: 5,
    svgKey: "noodle",
    priceOptions: [
      { label: null, amountMinor: 2500, currency: "HKD", sortOrder: 0 },
      { label: "熱飲", amountMinor: 2800, currency: "HKD", sortOrder: 1 },
      { label: "即磨咖啡", amountMinor: 3000, currency: "HKD", sortOrder: 2 },
      { label: "凍飲", amountMinor: 3000, currency: "HKD", sortOrder: 3 },
      { label: "汽水", amountMinor: 3000, currency: "HKD", sortOrder: 4 },
      { label: "特飲", amountMinor: 3500, currency: "HKD", sortOrder: 5 },
    ],
  },
  {
    name: "炸菜肉絲公仔麵",
    mealPeriods: ["breakfast"],
    sortOrder: 6,
    svgKey: "noodle",
    priceOptions: [
      { label: null, amountMinor: 2500, currency: "HKD", sortOrder: 0 },
      { label: "熱飲", amountMinor: 2800, currency: "HKD", sortOrder: 1 },
      { label: "即磨咖啡", amountMinor: 3000, currency: "HKD", sortOrder: 2 },
      { label: "凍飲", amountMinor: 3000, currency: "HKD", sortOrder: 3 },
      { label: "汽水", amountMinor: 3000, currency: "HKD", sortOrder: 4 },
      { label: "特飲", amountMinor: 3500, currency: "HKD", sortOrder: 5 },
    ],
  },
  {
    name: "五香肉丁公仔麵",
    mealPeriods: ["breakfast"],
    sortOrder: 7,
    svgKey: "noodle",
    priceOptions: [
      { label: null, amountMinor: 2500, currency: "HKD", sortOrder: 0 },
      { label: "熱飲", amountMinor: 2800, currency: "HKD", sortOrder: 1 },
      { label: "即磨咖啡", amountMinor: 3000, currency: "HKD", sortOrder: 2 },
      { label: "凍飲", amountMinor: 3000, currency: "HKD", sortOrder: 3 },
      { label: "汽水", amountMinor: 3000, currency: "HKD", sortOrder: 4 },
      { label: "特飲", amountMinor: 3500, currency: "HKD", sortOrder: 5 },
    ],
  },
  {
    name: "火腿煎蛋公仔麵",
    mealPeriods: ["breakfast"],
    sortOrder: 8,
    svgKey: "noodle",
    priceOptions: [
      { label: null, amountMinor: 2700, currency: "HKD", sortOrder: 0 },
      { label: "熱飲", amountMinor: 3000, currency: "HKD", sortOrder: 1 },
      { label: "即磨咖啡", amountMinor: 3200, currency: "HKD", sortOrder: 2 },
      { label: "凍飲", amountMinor: 3200, currency: "HKD", sortOrder: 3 },
      { label: "汽水", amountMinor: 3200, currency: "HKD", sortOrder: 4 },
      { label: "特飲", amountMinor: 3700, currency: "HKD", sortOrder: 5 },
    ],
  },
  {
    name: "午餐肉煎蛋公仔麵",
    mealPeriods: ["breakfast"],
    sortOrder: 9,
    svgKey: "noodle",
    priceOptions: [
      { label: null, amountMinor: 2700, currency: "HKD", sortOrder: 0 },
      { label: "熱飲", amountMinor: 3000, currency: "HKD", sortOrder: 1 },
      { label: "即磨咖啡", amountMinor: 3200, currency: "HKD", sortOrder: 2 },
      { label: "凍飲", amountMinor: 3200, currency: "HKD", sortOrder: 3 },
      { label: "汽水", amountMinor: 3200, currency: "HKD", sortOrder: 4 },
      { label: "特飲", amountMinor: 3700, currency: "HKD", sortOrder: 5 },
    ],
  },
  {
    name: "腸仔煎蛋公仔麵",
    mealPeriods: ["breakfast"],
    sortOrder: 10,
    svgKey: "noodle",
    priceOptions: [
      { label: null, amountMinor: 2700, currency: "HKD", sortOrder: 0 },
      { label: "熱飲", amountMinor: 3000, currency: "HKD", sortOrder: 1 },
      { label: "即磨咖啡", amountMinor: 3200, currency: "HKD", sortOrder: 2 },
      { label: "凍飲", amountMinor: 3200, currency: "HKD", sortOrder: 3 },
      { label: "汽水", amountMinor: 3200, currency: "HKD", sortOrder: 4 },
      { label: "特飲", amountMinor: 3700, currency: "HKD", sortOrder: 5 },
    ],
  },
  {
    name: "粟米豬肉蒸餃（8隻）",
    mealPeriods: ["breakfast"],
    sortOrder: 11,
    svgKey: "default",
    priceOptions: [
      { label: null, amountMinor: 2900, currency: "HKD", sortOrder: 0 },
      { label: "熱飲", amountMinor: 3200, currency: "HKD", sortOrder: 1 },
      { label: "即磨咖啡", amountMinor: 3400, currency: "HKD", sortOrder: 2 },
      { label: "凍飲", amountMinor: 3400, currency: "HKD", sortOrder: 3 },
      { label: "汽水", amountMinor: 3400, currency: "HKD", sortOrder: 4 },
      { label: "特飲", amountMinor: 3900, currency: "HKD", sortOrder: 5 },
    ],
  },
  {
    name: "轉出前一丁",
    mealPeriods: ["breakfast"],
    sortOrder: 12,
    svgKey: "noodle",
    priceOptions: [
      { label: null, amountMinor: 300, currency: "HKD", sortOrder: 0 },
    ],
  },
  {
    name: "蒜蓉雞扒飯",
    mealPeriods: ["lunch", "dinner"],
    sortOrder: 13,
    svgKey: "rice",
    priceOptions: [
      { label: "熱飲", amountMinor: 3800, currency: "HKD", sortOrder: 0 },
      { label: "即磨咖啡", amountMinor: 4100, currency: "HKD", sortOrder: 1 },
      { label: "凍飲", amountMinor: 4200, currency: "HKD", sortOrder: 2 },
      { label: "汽水", amountMinor: 4200, currency: "HKD", sortOrder: 3 },
      { label: "特飲", amountMinor: 4600, currency: "HKD", sortOrder: 4 },
    ],
  },
  {
    name: "兩餸飯",
    mealPeriods: ["lunch", "dinner"],
    sortOrder: 14,
    svgKey: "rice",
    priceOptions: [
      { label: "熱飲", amountMinor: 3400, currency: "HKD", sortOrder: 0 },
      { label: "即磨咖啡", amountMinor: 3700, currency: "HKD", sortOrder: 1 },
      { label: "凍飲", amountMinor: 3800, currency: "HKD", sortOrder: 2 },
      { label: "汽水", amountMinor: 3800, currency: "HKD", sortOrder: 3 },
      { label: "特飲", amountMinor: 4200, currency: "HKD", sortOrder: 4 },
    ],
  },
  {
    name: "三餸飯",
    mealPeriods: ["lunch", "dinner"],
    sortOrder: 15,
    svgKey: "rice",
    priceOptions: [
      { label: "熱飲", amountMinor: 4100, currency: "HKD", sortOrder: 0 },
      { label: "即磨咖啡", amountMinor: 4400, currency: "HKD", sortOrder: 1 },
      { label: "凍飲", amountMinor: 4500, currency: "HKD", sortOrder: 2 },
      { label: "汽水", amountMinor: 4500, currency: "HKD", sortOrder: 3 },
      { label: "特飲", amountMinor: 4900, currency: "HKD", sortOrder: 4 },
    ],
  },
  {
    name: "肉絲燜伊麵",
    mealPeriods: ["lunch"],
    sortOrder: 16,
    svgKey: "noodle",
    priceOptions: [
      { label: "熱飲", amountMinor: 4300, currency: "HKD", sortOrder: 0 },
      { label: "即磨咖啡", amountMinor: 4600, currency: "HKD", sortOrder: 1 },
      { label: "凍飲", amountMinor: 4700, currency: "HKD", sortOrder: 2 },
      { label: "汽水", amountMinor: 4700, currency: "HKD", sortOrder: 3 },
      { label: "特飲", amountMinor: 5100, currency: "HKD", sortOrder: 4 },
    ],
  },
  {
    name: "五香肉丁炒飯",
    mealPeriods: ["lunch"],
    sortOrder: 17,
    svgKey: "rice",
    priceOptions: [
      { label: "熱飲", amountMinor: 4300, currency: "HKD", sortOrder: 0 },
      { label: "即磨咖啡", amountMinor: 4600, currency: "HKD", sortOrder: 1 },
      { label: "凍飲", amountMinor: 4700, currency: "HKD", sortOrder: 2 },
      { label: "汽水", amountMinor: 4700, currency: "HKD", sortOrder: 3 },
      { label: "特飲", amountMinor: 5100, currency: "HKD", sortOrder: 4 },
    ],
  },
  {
    name: "醬皇牛肚米線",
    mealPeriods: ["lunch"],
    sortOrder: 18,
    svgKey: "noodle",
    priceOptions: [
      { label: "熱飲", amountMinor: 4100, currency: "HKD", sortOrder: 0 },
      { label: "即磨咖啡", amountMinor: 4400, currency: "HKD", sortOrder: 1 },
      { label: "凍飲", amountMinor: 4500, currency: "HKD", sortOrder: 2 },
      { label: "汽水", amountMinor: 4500, currency: "HKD", sortOrder: 3 },
      { label: "特飲", amountMinor: 4900, currency: "HKD", sortOrder: 4 },
    ],
  },
  {
    name: "香菇貢丸米線",
    mealPeriods: ["lunch"],
    sortOrder: 19,
    svgKey: "noodle",
    priceOptions: [
      { label: "熱飲", amountMinor: 4100, currency: "HKD", sortOrder: 0 },
      { label: "即磨咖啡", amountMinor: 4400, currency: "HKD", sortOrder: 1 },
      { label: "凍飲", amountMinor: 4500, currency: "HKD", sortOrder: 2 },
      { label: "汽水", amountMinor: 4500, currency: "HKD", sortOrder: 3 },
      { label: "特飲", amountMinor: 4900, currency: "HKD", sortOrder: 4 },
    ],
  },
  {
    name: "肥牛米線",
    mealPeriods: ["lunch"],
    sortOrder: 20,
    svgKey: "noodle",
    priceOptions: [
      { label: "熱飲", amountMinor: 3900, currency: "HKD", sortOrder: 0 },
      { label: "即磨咖啡", amountMinor: 4200, currency: "HKD", sortOrder: 1 },
      { label: "凍飲", amountMinor: 4300, currency: "HKD", sortOrder: 2 },
      { label: "汽水", amountMinor: 4300, currency: "HKD", sortOrder: 3 },
      { label: "特飲", amountMinor: 4700, currency: "HKD", sortOrder: 4 },
    ],
  },
  {
    name: "口水雞米線",
    mealPeriods: ["lunch"],
    sortOrder: 21,
    svgKey: "noodle",
    priceOptions: [
      { label: "熱飲", amountMinor: 4100, currency: "HKD", sortOrder: 0 },
      { label: "即磨咖啡", amountMinor: 4400, currency: "HKD", sortOrder: 1 },
      { label: "凍飲", amountMinor: 4500, currency: "HKD", sortOrder: 2 },
      { label: "汽水", amountMinor: 4500, currency: "HKD", sortOrder: 3 },
      { label: "特飲", amountMinor: 4900, currency: "HKD", sortOrder: 4 },
    ],
  },
  {
    name: "醬爆牛筋丸米線",
    mealPeriods: ["lunch"],
    sortOrder: 22,
    svgKey: "noodle",
    priceOptions: [
      { label: "熱飲", amountMinor: 3900, currency: "HKD", sortOrder: 0 },
      { label: "即磨咖啡", amountMinor: 4200, currency: "HKD", sortOrder: 1 },
      { label: "凍飲", amountMinor: 4300, currency: "HKD", sortOrder: 2 },
      { label: "汽水", amountMinor: 4300, currency: "HKD", sortOrder: 3 },
      { label: "特飲", amountMinor: 4700, currency: "HKD", sortOrder: 4 },
    ],
  },
  {
    name: "招牌豬排米線",
    mealPeriods: ["lunch"],
    sortOrder: 23,
    svgKey: "noodle",
    priceOptions: [
      { label: "熱飲", amountMinor: 3900, currency: "HKD", sortOrder: 0 },
      { label: "即磨咖啡", amountMinor: 4200, currency: "HKD", sortOrder: 1 },
      { label: "凍飲", amountMinor: 4300, currency: "HKD", sortOrder: 2 },
      { label: "汽水", amountMinor: 4300, currency: "HKD", sortOrder: 3 },
      { label: "特飲", amountMinor: 4700, currency: "HKD", sortOrder: 4 },
    ],
  },
  {
    name: "五香牛腱米線",
    mealPeriods: ["lunch"],
    sortOrder: 24,
    svgKey: "noodle",
    priceOptions: [
      { label: "熱飲", amountMinor: 4100, currency: "HKD", sortOrder: 0 },
      { label: "即磨咖啡", amountMinor: 4400, currency: "HKD", sortOrder: 1 },
      { label: "凍飲", amountMinor: 4500, currency: "HKD", sortOrder: 2 },
      { label: "汽水", amountMinor: 4500, currency: "HKD", sortOrder: 3 },
      { label: "特飲", amountMinor: 4900, currency: "HKD", sortOrder: 4 },
    ],
  },
  {
    name: "餃子米線",
    mealPeriods: ["lunch"],
    sortOrder: 25,
    svgKey: "noodle",
    priceOptions: [
      { label: "熱飲", amountMinor: 4100, currency: "HKD", sortOrder: 0 },
      { label: "即磨咖啡", amountMinor: 4400, currency: "HKD", sortOrder: 1 },
      { label: "凍飲", amountMinor: 4500, currency: "HKD", sortOrder: 2 },
      { label: "汽水", amountMinor: 4500, currency: "HKD", sortOrder: 3 },
      { label: "特飲", amountMinor: 4900, currency: "HKD", sortOrder: 4 },
    ],
  },
  {
    name: "紅燒豬大腸米線",
    mealPeriods: ["lunch"],
    sortOrder: 26,
    svgKey: "noodle",
    priceOptions: [
      { label: "熱飲", amountMinor: 4100, currency: "HKD", sortOrder: 0 },
      { label: "即磨咖啡", amountMinor: 4400, currency: "HKD", sortOrder: 1 },
      { label: "凍飲", amountMinor: 4500, currency: "HKD", sortOrder: 2 },
      { label: "汽水", amountMinor: 4500, currency: "HKD", sortOrder: 3 },
      { label: "特飲", amountMinor: 4900, currency: "HKD", sortOrder: 4 },
    ],
  },
  {
    name: "苗家紅燒牛肉米線",
    mealPeriods: ["lunch"],
    sortOrder: 27,
    svgKey: "noodle",
    priceOptions: [
      { label: "熱飲", amountMinor: 4100, currency: "HKD", sortOrder: 0 },
      { label: "即磨咖啡", amountMinor: 4400, currency: "HKD", sortOrder: 1 },
      { label: "凍飲", amountMinor: 4500, currency: "HKD", sortOrder: 2 },
      { label: "汽水", amountMinor: 4500, currency: "HKD", sortOrder: 3 },
      { label: "特飲", amountMinor: 4900, currency: "HKD", sortOrder: 4 },
    ],
  },
  {
    name: "滷水雞翼米線",
    mealPeriods: ["lunch"],
    sortOrder: 28,
    svgKey: "noodle",
    priceOptions: [
      { label: "熱飲", amountMinor: 4100, currency: "HKD", sortOrder: 0 },
      { label: "即磨咖啡", amountMinor: 4400, currency: "HKD", sortOrder: 1 },
      { label: "凍飲", amountMinor: 4500, currency: "HKD", sortOrder: 2 },
      { label: "汽水", amountMinor: 4500, currency: "HKD", sortOrder: 3 },
      { label: "特飲", amountMinor: 4900, currency: "HKD", sortOrder: 4 },
    ],
  },
  {
    name: "魚腐米線",
    mealPeriods: ["lunch"],
    sortOrder: 29,
    svgKey: "noodle",
    priceOptions: [
      { label: "熱飲", amountMinor: 4100, currency: "HKD", sortOrder: 0 },
      { label: "即磨咖啡", amountMinor: 4400, currency: "HKD", sortOrder: 1 },
      { label: "凍飲", amountMinor: 4500, currency: "HKD", sortOrder: 2 },
      { label: "汽水", amountMinor: 4500, currency: "HKD", sortOrder: 3 },
      { label: "特飲", amountMinor: 4900, currency: "HKD", sortOrder: 4 },
    ],
  },
  {
    name: "魚片魚蛋米線",
    mealPeriods: ["lunch"],
    sortOrder: 30,
    svgKey: "noodle",
    priceOptions: [
      { label: "熱飲", amountMinor: 4100, currency: "HKD", sortOrder: 0 },
      { label: "即磨咖啡", amountMinor: 4400, currency: "HKD", sortOrder: 1 },
      { label: "凍飲", amountMinor: 4500, currency: "HKD", sortOrder: 2 },
      { label: "汽水", amountMinor: 4500, currency: "HKD", sortOrder: 3 },
      { label: "特飲", amountMinor: 4900, currency: "HKD", sortOrder: 4 },
    ],
  },
  {
    name: "豬手米線",
    mealPeriods: ["lunch"],
    sortOrder: 31,
    svgKey: "noodle",
    priceOptions: [
      { label: "熱飲", amountMinor: 4100, currency: "HKD", sortOrder: 0 },
      { label: "即磨咖啡", amountMinor: 4400, currency: "HKD", sortOrder: 1 },
      { label: "凍飲", amountMinor: 4500, currency: "HKD", sortOrder: 2 },
      { label: "汽水", amountMinor: 4500, currency: "HKD", sortOrder: 3 },
      { label: "特飲", amountMinor: 4900, currency: "HKD", sortOrder: 4 },
    ],
  },
  {
    name: "轉烏冬／出前一丁",
    mealPeriods: ["lunch"],
    sortOrder: 32,
    svgKey: "noodle",
    priceOptions: [
      { label: null, amountMinor: 300, currency: "HKD", sortOrder: 0 },
    ],
  },
  {
    name: "轉辛辣麵／紅薯粉／手工麵",
    mealPeriods: ["lunch"],
    sortOrder: 33,
    svgKey: "noodle",
    priceOptions: [
      { label: null, amountMinor: 500, currency: "HKD", sortOrder: 0 },
    ],
  },
  {
    name: "加紫菜／生菜",
    mealPeriods: ["lunch"],
    sortOrder: 34,
    svgKey: "default",
    priceOptions: [
      { label: null, amountMinor: 800, currency: "HKD", sortOrder: 0 },
    ],
  },
  {
    name: "加滷蛋",
    mealPeriods: ["lunch"],
    sortOrder: 35,
    svgKey: "default",
    priceOptions: [
      { label: null, amountMinor: 500, currency: "HKD", sortOrder: 0 },
    ],
  },
  {
    name: "接骨木花梳打",
    mealPeriods: ["lunch"],
    sortOrder: 36,
    svgKey: "drink",
    priceOptions: [
      { label: "單點", amountMinor: 1500, currency: "HKD", sortOrder: 0 },
      { label: "跟餐加配", amountMinor: 800, currency: "HKD", sortOrder: 1 },
    ],
  },
  {
    name: "水蜜桃梳打",
    mealPeriods: ["lunch"],
    sortOrder: 37,
    svgKey: "drink",
    priceOptions: [
      { label: "單點", amountMinor: 1500, currency: "HKD", sortOrder: 0 },
      { label: "跟餐加配", amountMinor: 800, currency: "HKD", sortOrder: 1 },
    ],
  },
  {
    name: "香芒果梳打",
    mealPeriods: ["lunch"],
    sortOrder: 38,
    svgKey: "drink",
    priceOptions: [
      { label: "單點", amountMinor: 1500, currency: "HKD", sortOrder: 0 },
      { label: "跟餐加配", amountMinor: 800, currency: "HKD", sortOrder: 1 },
    ],
  },
  {
    name: "百香果梳打",
    mealPeriods: ["lunch"],
    sortOrder: 39,
    svgKey: "drink",
    priceOptions: [
      { label: "單點", amountMinor: 1500, currency: "HKD", sortOrder: 0 },
      { label: "跟餐加配", amountMinor: 800, currency: "HKD", sortOrder: 1 },
    ],
  },
  {
    name: "柚子蜜梳打",
    mealPeriods: ["lunch"],
    sortOrder: 40,
    svgKey: "drink",
    priceOptions: [
      { label: "單點", amountMinor: 1500, currency: "HKD", sortOrder: 0 },
      { label: "跟餐加配", amountMinor: 800, currency: "HKD", sortOrder: 1 },
    ],
  },
  {
    name: "草莓梳打",
    mealPeriods: ["lunch"],
    sortOrder: 41,
    svgKey: "drink",
    priceOptions: [
      { label: "單點", amountMinor: 1500, currency: "HKD", sortOrder: 0 },
      { label: "跟餐加配", amountMinor: 800, currency: "HKD", sortOrder: 1 },
    ],
  },
  {
    name: "黑加侖子梳打",
    mealPeriods: ["lunch"],
    sortOrder: 42,
    svgKey: "drink",
    priceOptions: [
      { label: "單點", amountMinor: 1500, currency: "HKD", sortOrder: 0 },
      { label: "跟餐加配", amountMinor: 800, currency: "HKD", sortOrder: 1 },
    ],
  },
  {
    name: "蜂蜜白提梳打",
    mealPeriods: ["lunch"],
    sortOrder: 43,
    svgKey: "drink",
    priceOptions: [
      { label: "單點", amountMinor: 1500, currency: "HKD", sortOrder: 0 },
      { label: "跟餐加配", amountMinor: 800, currency: "HKD", sortOrder: 1 },
    ],
  },
  {
    name: "椰汁紅豆冰",
    mealPeriods: ["lunch"],
    sortOrder: 44,
    svgKey: "drink",
    priceOptions: [
      { label: "單點", amountMinor: 1500, currency: "HKD", sortOrder: 0 },
      { label: "跟餐加配", amountMinor: 800, currency: "HKD", sortOrder: 1 },
    ],
  },
  {
    name: "檸檬可樂",
    mealPeriods: ["lunch"],
    sortOrder: 45,
    svgKey: "drink",
    priceOptions: [
      { label: "單點", amountMinor: 1500, currency: "HKD", sortOrder: 0 },
      { label: "跟餐加配", amountMinor: 800, currency: "HKD", sortOrder: 1 },
    ],
  },
  {
    name: "凍檸樂",
    mealPeriods: ["lunch"],
    sortOrder: 46,
    svgKey: "drink",
    priceOptions: [
      { label: "單點", amountMinor: 1500, currency: "HKD", sortOrder: 0 },
      { label: "跟餐加配", amountMinor: 800, currency: "HKD", sortOrder: 1 },
    ],
  },
  {
    name: "無糖凍檸樂",
    mealPeriods: ["lunch"],
    sortOrder: 47,
    svgKey: "drink",
    priceOptions: [
      { label: "單點", amountMinor: 1500, currency: "HKD", sortOrder: 0 },
      { label: "跟餐加配", amountMinor: 800, currency: "HKD", sortOrder: 1 },
    ],
  },
  {
    name: "檸檬雪碧",
    mealPeriods: ["lunch"],
    sortOrder: 48,
    svgKey: "drink",
    priceOptions: [
      { label: "單點", amountMinor: 1500, currency: "HKD", sortOrder: 0 },
      { label: "跟餐加配", amountMinor: 800, currency: "HKD", sortOrder: 1 },
    ],
  },
  {
    name: "鹹檸檬可樂",
    mealPeriods: ["lunch"],
    sortOrder: 49,
    svgKey: "drink",
    priceOptions: [
      { label: "單點", amountMinor: 1500, currency: "HKD", sortOrder: 0 },
      { label: "跟餐加配", amountMinor: 800, currency: "HKD", sortOrder: 1 },
    ],
  },
  {
    name: "鹹檸檬雪碧",
    mealPeriods: ["lunch"],
    sortOrder: 50,
    svgKey: "drink",
    priceOptions: [
      { label: "單點", amountMinor: 1500, currency: "HKD", sortOrder: 0 },
      { label: "跟餐加配", amountMinor: 800, currency: "HKD", sortOrder: 1 },
    ],
  },
  {
    name: "龍鳳可樂",
    mealPeriods: ["lunch"],
    sortOrder: 51,
    svgKey: "drink",
    priceOptions: [
      { label: "單點", amountMinor: 1500, currency: "HKD", sortOrder: 0 },
      { label: "跟餐加配", amountMinor: 800, currency: "HKD", sortOrder: 1 },
    ],
  },
  {
    name: "龍鳳雪碧",
    mealPeriods: ["lunch"],
    sortOrder: 52,
    svgKey: "drink",
    priceOptions: [
      { label: "單點", amountMinor: 1500, currency: "HKD", sortOrder: 0 },
      { label: "跟餐加配", amountMinor: 800, currency: "HKD", sortOrder: 1 },
    ],
  },
  {
    name: "紅豆冰",
    mealPeriods: ["lunch"],
    sortOrder: 53,
    svgKey: "drink",
    priceOptions: [
      { label: "單點", amountMinor: 1500, currency: "HKD", sortOrder: 0 },
      { label: "跟餐加配", amountMinor: 800, currency: "HKD", sortOrder: 1 },
    ],
  },
  {
    name: "咖啡紅豆冰",
    mealPeriods: ["lunch"],
    sortOrder: 54,
    svgKey: "drink",
    priceOptions: [
      { label: "單點", amountMinor: 1500, currency: "HKD", sortOrder: 0 },
      { label: "跟餐加配", amountMinor: 800, currency: "HKD", sortOrder: 1 },
    ],
  },
  {
    name: "鴛鴦紅豆冰",
    mealPeriods: ["lunch"],
    sortOrder: 55,
    svgKey: "drink",
    priceOptions: [
      { label: "單點", amountMinor: 1500, currency: "HKD", sortOrder: 0 },
      { label: "跟餐加配", amountMinor: 800, currency: "HKD", sortOrder: 1 },
    ],
  },
  {
    name: "黑糖珍珠奶茶",
    mealPeriods: ["lunch"],
    sortOrder: 56,
    svgKey: "drink",
    priceOptions: [
      { label: "跟餐", amountMinor: 1000, currency: "HKD", sortOrder: 0 },
      { label: "單點", amountMinor: 1500, currency: "HKD", sortOrder: 1 },
    ],
  },
  {
    name: "雪碧",
    mealPeriods: ["lunch"],
    sortOrder: 57,
    svgKey: "drink",
    priceOptions: [
      { label: "單點", amountMinor: 1000, currency: "HKD", sortOrder: 0 },
      { label: "跟餐配", amountMinor: 400, currency: "HKD", sortOrder: 1 },
    ],
  },
  {
    name: "芬達",
    mealPeriods: ["lunch"],
    sortOrder: 58,
    svgKey: "drink",
    priceOptions: [
      { label: "單點", amountMinor: 1000, currency: "HKD", sortOrder: 0 },
      { label: "跟餐配", amountMinor: 400, currency: "HKD", sortOrder: 1 },
    ],
  },
  {
    name: "可樂",
    mealPeriods: ["lunch"],
    sortOrder: 59,
    svgKey: "drink",
    priceOptions: [
      { label: "單點", amountMinor: 1000, currency: "HKD", sortOrder: 0 },
      { label: "跟餐配", amountMinor: 400, currency: "HKD", sortOrder: 1 },
    ],
  },
  {
    name: "梳打水",
    mealPeriods: ["lunch"],
    sortOrder: 60,
    svgKey: "drink",
    priceOptions: [
      { label: "單點", amountMinor: 1000, currency: "HKD", sortOrder: 0 },
      { label: "跟餐配", amountMinor: 400, currency: "HKD", sortOrder: 1 },
    ],
  },
  {
    name: "香濃奶茶",
    mealPeriods: ["lunch"],
    sortOrder: 61,
    svgKey: "drink",
    priceOptions: [
      { label: "熱／單點", amountMinor: 800, currency: "HKD", sortOrder: 0 },
      { label: "凍／單點", amountMinor: 1000, currency: "HKD", sortOrder: 1 },
      { label: "熱／加配", amountMinor: 0, currency: "HKD", sortOrder: 2 },
      { label: "凍／加配", amountMinor: 400, currency: "HKD", sortOrder: 3 },
    ],
  },
  {
    name: "港產鴛鴦",
    mealPeriods: ["lunch"],
    sortOrder: 62,
    svgKey: "drink",
    priceOptions: [
      { label: "熱／單點", amountMinor: 800, currency: "HKD", sortOrder: 0 },
      { label: "凍／單點", amountMinor: 1000, currency: "HKD", sortOrder: 1 },
      { label: "熱／加配", amountMinor: 0, currency: "HKD", sortOrder: 2 },
      { label: "凍／加配", amountMinor: 400, currency: "HKD", sortOrder: 3 },
    ],
  },
  {
    name: "檸檬茶",
    mealPeriods: ["lunch"],
    sortOrder: 63,
    svgKey: "drink",
    priceOptions: [
      { label: "熱／單點", amountMinor: 800, currency: "HKD", sortOrder: 0 },
      { label: "凍／單點", amountMinor: 1000, currency: "HKD", sortOrder: 1 },
      { label: "熱／加配", amountMinor: 0, currency: "HKD", sortOrder: 2 },
      { label: "凍／加配", amountMinor: 400, currency: "HKD", sortOrder: 3 },
    ],
  },
  {
    name: "檸檬水",
    mealPeriods: ["lunch"],
    sortOrder: 64,
    svgKey: "drink",
    priceOptions: [
      { label: "熱／單點", amountMinor: 800, currency: "HKD", sortOrder: 0 },
      { label: "凍／單點", amountMinor: 1000, currency: "HKD", sortOrder: 1 },
      { label: "熱／加配", amountMinor: 0, currency: "HKD", sortOrder: 2 },
      { label: "凍／加配", amountMinor: 400, currency: "HKD", sortOrder: 3 },
    ],
  },
  {
    name: "西洋菜蜜",
    mealPeriods: ["lunch"],
    sortOrder: 65,
    svgKey: "drink",
    priceOptions: [
      { label: "熱／單點", amountMinor: 800, currency: "HKD", sortOrder: 0 },
      { label: "凍／單點", amountMinor: 1000, currency: "HKD", sortOrder: 1 },
      { label: "熱／加配", amountMinor: 0, currency: "HKD", sortOrder: 2 },
      { label: "凍／加配", amountMinor: 400, currency: "HKD", sortOrder: 3 },
    ],
  },
  {
    name: "檸檬蜜",
    mealPeriods: ["lunch"],
    sortOrder: 66,
    svgKey: "drink",
    priceOptions: [
      { label: "熱／單點", amountMinor: 800, currency: "HKD", sortOrder: 0 },
      { label: "凍／單點", amountMinor: 1000, currency: "HKD", sortOrder: 1 },
      { label: "熱／加配", amountMinor: 0, currency: "HKD", sortOrder: 2 },
      { label: "凍／加配", amountMinor: 400, currency: "HKD", sortOrder: 3 },
    ],
  },
  {
    name: "養顏杏霜",
    mealPeriods: ["lunch"],
    sortOrder: 67,
    svgKey: "drink",
    priceOptions: [
      { label: "熱／單點", amountMinor: 800, currency: "HKD", sortOrder: 0 },
      { label: "凍／單點", amountMinor: 1000, currency: "HKD", sortOrder: 1 },
      { label: "熱／加配", amountMinor: 0, currency: "HKD", sortOrder: 2 },
      { label: "凍／加配", amountMinor: 400, currency: "HKD", sortOrder: 3 },
    ],
  },
  {
    name: "檸檬利賓納",
    mealPeriods: ["lunch"],
    sortOrder: 68,
    svgKey: "drink",
    priceOptions: [
      { label: "熱／單點", amountMinor: 800, currency: "HKD", sortOrder: 0 },
      { label: "凍／單點", amountMinor: 1000, currency: "HKD", sortOrder: 1 },
      { label: "熱／加配", amountMinor: 0, currency: "HKD", sortOrder: 2 },
      { label: "凍／加配", amountMinor: 400, currency: "HKD", sortOrder: 3 },
    ],
  },
  {
    name: "利賓納",
    mealPeriods: ["lunch"],
    sortOrder: 69,
    svgKey: "drink",
    priceOptions: [
      { label: "熱／單點", amountMinor: 800, currency: "HKD", sortOrder: 0 },
      { label: "凍／單點", amountMinor: 1000, currency: "HKD", sortOrder: 1 },
      { label: "熱／加配", amountMinor: 0, currency: "HKD", sortOrder: 2 },
      { label: "凍／加配", amountMinor: 400, currency: "HKD", sortOrder: 3 },
    ],
  },
  {
    name: "阿華田",
    mealPeriods: ["lunch"],
    sortOrder: 70,
    svgKey: "drink",
    priceOptions: [
      { label: "熱／單點", amountMinor: 800, currency: "HKD", sortOrder: 0 },
      { label: "凍／單點", amountMinor: 1000, currency: "HKD", sortOrder: 1 },
      { label: "熱／加配", amountMinor: 0, currency: "HKD", sortOrder: 2 },
      { label: "凍／加配", amountMinor: 400, currency: "HKD", sortOrder: 3 },
    ],
  },
  {
    name: "好立克",
    mealPeriods: ["lunch"],
    sortOrder: 71,
    svgKey: "drink",
    priceOptions: [
      { label: "熱／單點", amountMinor: 800, currency: "HKD", sortOrder: 0 },
      { label: "凍／單點", amountMinor: 1000, currency: "HKD", sortOrder: 1 },
      { label: "熱／加配", amountMinor: 0, currency: "HKD", sortOrder: 2 },
      { label: "凍／加配", amountMinor: 400, currency: "HKD", sortOrder: 3 },
    ],
  },
  {
    name: "朱古力",
    mealPeriods: ["lunch"],
    sortOrder: 72,
    svgKey: "drink",
    priceOptions: [
      { label: "熱／單點", amountMinor: 800, currency: "HKD", sortOrder: 0 },
      { label: "凍／單點", amountMinor: 1000, currency: "HKD", sortOrder: 1 },
      { label: "熱／加配", amountMinor: 0, currency: "HKD", sortOrder: 2 },
      { label: "凍／加配", amountMinor: 400, currency: "HKD", sortOrder: 3 },
    ],
  },
  {
    name: "柚子蜜",
    mealPeriods: ["lunch"],
    sortOrder: 73,
    svgKey: "drink",
    priceOptions: [
      { label: "熱／單點", amountMinor: 800, currency: "HKD", sortOrder: 0 },
      { label: "凍／單點", amountMinor: 1000, currency: "HKD", sortOrder: 1 },
      { label: "熱／加配", amountMinor: 0, currency: "HKD", sortOrder: 2 },
      { label: "凍／加配", amountMinor: 400, currency: "HKD", sortOrder: 3 },
    ],
  },
  {
    name: "百香果",
    mealPeriods: ["lunch"],
    sortOrder: 74,
    svgKey: "drink",
    priceOptions: [
      { label: "熱／單點", amountMinor: 800, currency: "HKD", sortOrder: 0 },
      { label: "凍／單點", amountMinor: 1000, currency: "HKD", sortOrder: 1 },
      { label: "熱／加配", amountMinor: 0, currency: "HKD", sortOrder: 2 },
      { label: "凍／加配", amountMinor: 400, currency: "HKD", sortOrder: 3 },
    ],
  },
  {
    name: "即磨咖啡",
    mealPeriods: ["lunch"],
    sortOrder: 75,
    svgKey: "drink",
    priceOptions: [
      { label: "熱／單點", amountMinor: 800, currency: "HKD", sortOrder: 0 },
      { label: "凍／單點", amountMinor: 1000, currency: "HKD", sortOrder: 1 },
      { label: "加配", amountMinor: 300, currency: "HKD", sortOrder: 2 },
    ],
  },
  {
    name: "意式咖啡",
    mealPeriods: ["lunch"],
    sortOrder: 76,
    svgKey: "drink",
    priceOptions: [
      { label: "跟餐加配", amountMinor: 300, currency: "HKD", sortOrder: 0 },
    ],
  },
  {
    name: "椰香布丁",
    mealPeriods: ["lunch"],
    sortOrder: 77,
    svgKey: "dessert",
    priceOptions: [
      { label: "芒果", amountMinor: 1000, currency: "HKD", sortOrder: 0 },
      { label: "草莓", amountMinor: 1000, currency: "HKD", sortOrder: 1 },
      { label: "柚子", amountMinor: 1000, currency: "HKD", sortOrder: 2 },
      { label: "紅豆", amountMinor: 1000, currency: "HKD", sortOrder: 3 },
      { label: "椰汁", amountMinor: 1000, currency: "HKD", sortOrder: 4 },
      { label: "百香果", amountMinor: 1000, currency: "HKD", sortOrder: 5 },
      { label: "水蜜桃", amountMinor: 1000, currency: "HKD", sortOrder: 6 },
    ],
  },
  {
    name: "餃子",
    mealPeriods: ["dinner"],
    sortOrder: 81,
    svgKey: "default",
    priceOptions: [
      { label: "8隻", amountMinor: 4400, currency: "HKD", sortOrder: 0 },
      { label: "12隻", amountMinor: 6000, currency: "HKD", sortOrder: 1 },
      { label: "16隻", amountMinor: 7000, currency: "HKD", sortOrder: 2 },
      { label: "18隻", amountMinor: 7700, currency: "HKD", sortOrder: 3 },
    ],
  },
  {
    name: "湖南小炒肉",
    mealPeriods: ["dinner"],
    sortOrder: 82,
    svgKey: "default",
    priceOptions: [
      { label: null, amountMinor: 7000, currency: "HKD", sortOrder: 0 },
    ],
  },
  {
    name: "水煮生魚",
    mealPeriods: ["dinner"],
    sortOrder: 83,
    svgKey: "default",
    priceOptions: [
      { label: null, amountMinor: 6800, currency: "HKD", sortOrder: 0 },
    ],
  },
  {
    name: "土豆回鍋肉",
    mealPeriods: ["dinner"],
    sortOrder: 84,
    svgKey: "default",
    priceOptions: [
      { label: null, amountMinor: 6500, currency: "HKD", sortOrder: 0 },
    ],
  },
  {
    name: "清蒸鮮時魚",
    mealPeriods: ["dinner"],
    sortOrder: 85,
    svgKey: "default",
    priceOptions: [
      { label: null, amountMinor: 7000, currency: "HKD", sortOrder: 0 },
    ],
  },
  {
    name: "蒜蓉炒時蔬",
    mealPeriods: ["dinner"],
    sortOrder: 86,
    svgKey: "default",
    priceOptions: [
      { label: null, amountMinor: 5800, currency: "HKD", sortOrder: 0 },
    ],
  },
  {
    name: "青椒肉絲",
    mealPeriods: ["dinner"],
    sortOrder: 87,
    svgKey: "default",
    priceOptions: [
      { label: null, amountMinor: 6500, currency: "HKD", sortOrder: 0 },
    ],
  },
  {
    name: "腐乳通菜炒牛肉",
    mealPeriods: ["dinner"],
    sortOrder: 88,
    svgKey: "default",
    priceOptions: [
      { label: null, amountMinor: 6500, currency: "HKD", sortOrder: 0 },
    ],
  },
  {
    name: "椰菜花炒豬肉",
    mealPeriods: ["dinner"],
    sortOrder: 89,
    svgKey: "default",
    priceOptions: [
      { label: null, amountMinor: 6500, currency: "HKD", sortOrder: 0 },
    ],
  },
  {
    name: "水煮肥牛",
    mealPeriods: ["dinner"],
    sortOrder: 90,
    svgKey: "default",
    priceOptions: [
      { label: null, amountMinor: 6800, currency: "HKD", sortOrder: 0 },
    ],
  },
  {
    name: "加飯",
    mealPeriods: ["dinner"],
    sortOrder: 91,
    svgKey: "rice",
    priceOptions: [
      { label: null, amountMinor: 1000, currency: "HKD", sortOrder: 0 },
    ],
  },
  {
    name: "麻婆豆腐飯（學生特價）",
    mealPeriods: ["dinner"],
    sortOrder: 92,
    svgKey: "rice",
    priceOptions: [
      { label: "熱飲", amountMinor: 2200, currency: "HKD", sortOrder: 0 },
      { label: "即磨咖啡", amountMinor: 2500, currency: "HKD", sortOrder: 1 },
      { label: "凍飲", amountMinor: 2600, currency: "HKD", sortOrder: 2 },
      { label: "汽水", amountMinor: 2600, currency: "HKD", sortOrder: 3 },
      { label: "特飲", amountMinor: 3000, currency: "HKD", sortOrder: 4 },
    ],
  },
];
