import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

import {
  buildProfessorCatalog,
  isValidProfessorName,
  normalizeProfessorName,
  type CourseInstructorOverride,
  type TeachingStaffSource,
} from "./professor-catalog";

type Enrollment = {
  academicYear: string;
  term: string;
  courseCode: string;
  classCode: string;
  classNbr: string;
  component: string;
  section: string;
  quota: number;
  vacancy: number;
  instructors: string[];
};

export function renderProfessorImportSql(payload: object): string {
  const data = JSON.stringify(payload);
  if (data.includes("$professors$")) {
    throw new Error("Unexpected SQL dollar-quote marker in payload");
  }
  return `-- Generated by scripts/render-professor-import.ts. Review before applying.
begin;

create temp table _professor_import (payload jsonb not null) on commit drop;
insert into _professor_import values ($professors$${data}$professors$::jsonb);

do $validate$
begin
  if exists (
    select 1
    from _professor_import,
         jsonb_to_recordset(payload->'professors') as x(
           identity_profile_url text
         )
    left join staff_people person on person.profile_url = x.identity_profile_url
    where x.identity_profile_url is not null and person.id is null
  ) then
    raise exception 'Professor identity override references a missing staff profile';
  end if;
  if exists (
    select 1
    from _professor_import,
         jsonb_to_recordset(payload->'overrides') as x(profile_url text)
    left join staff_people person on person.profile_url = x.profile_url
    where person.id is null
  ) then
    raise exception 'Course instructor override references a missing staff profile';
  end if;
end
$validate$;

delete from professor_courses;
delete from course_enrollments;

insert into professors (id, name, search_text)
select x.id, x.name, x.search_text
from _professor_import,
     jsonb_to_recordset(payload->'professors') as x(
       id text, name text, search_text text, courses jsonb,
       identity_profile_url text, identity_evidence_url text
     )
on conflict (id) do update set
  name = excluded.name,
  search_text = excluded.search_text,
  updated_at = now();

insert into professor_courses (professor_id, course_code)
select x.id, course.value
from _professor_import,
     jsonb_to_recordset(payload->'professors') as x(
       id text, name text, search_text text, courses jsonb,
       identity_profile_url text, identity_evidence_url text
     ),
     lateral jsonb_array_elements_text(x.courses) course(value)
on conflict do nothing;

insert into professor_staff_identities (
  professor_id, person_id, match_method, source_url
)
select x.id, person.id, 'manual_override', x.identity_evidence_url
from _professor_import,
     jsonb_to_recordset(payload->'professors') as x(
       id text, name text, search_text text, courses jsonb,
       identity_profile_url text, identity_evidence_url text
     )
join staff_people person on person.profile_url = x.identity_profile_url
where x.identity_profile_url is not null
on conflict (professor_id) do update set
  person_id = excluded.person_id,
  match_method = excluded.match_method,
  source_url = excluded.source_url,
  verified_at = now();

insert into staff_people (id, canonical_name, source, identity_kind)
select 'timetable-professor:' || x.id, x.name, 'cuhk_timetable', 'unverified'
from _professor_import,
     jsonb_to_recordset(payload->'professors') as x(
       id text, name text, search_text text, courses jsonb,
       identity_profile_url text, identity_evidence_url text
     )
left join professor_staff_identities identity on identity.professor_id = x.id
left join staff_person_sources source
  on source.source = 'cuhk_timetable' and source.source_key = x.id
where identity.professor_id is null and source.source_key is null
on conflict (id) do update set
  canonical_name = excluded.canonical_name,
  last_seen_at = now(),
  is_current = true,
  missing_runs = 0,
  updated_at = now();

insert into staff_person_sources (person_id, source, source_key, source_url)
select 'timetable-professor:' || x.id, 'cuhk_timetable', x.id,
       'https://rgsntl.rgs.cuhk.edu.hk/rws_prd_applx2/Public/tt_dsp_timetable.aspx'
from _professor_import,
     jsonb_to_recordset(payload->'professors') as x(
       id text, name text, search_text text, courses jsonb,
       identity_profile_url text, identity_evidence_url text
     )
left join professor_staff_identities identity on identity.professor_id = x.id
where identity.professor_id is null
  and exists (
    select 1 from staff_people person
    where person.id = 'timetable-professor:' || x.id
  )
on conflict (source, source_key) do update set
  last_seen_at = now(), is_current = true, missing_runs = 0;

insert into professor_staff_identities (
  professor_id, person_id, match_method, source_url
)
select x.id, source.person_id, 'source_native', source.source_url
from _professor_import,
     jsonb_to_recordset(payload->'professors') as x(
       id text, name text, search_text text, courses jsonb,
       identity_profile_url text, identity_evidence_url text
     )
join staff_person_sources source
  on source.source = 'cuhk_timetable' and source.source_key = x.id
left join professor_staff_identities identity on identity.professor_id = x.id
where identity.professor_id is null
on conflict (professor_id) do nothing;

insert into course_instructors (person_id)
select distinct identity.person_id
from professor_staff_identities identity,
     _professor_import,
     jsonb_to_recordset(payload->'professors') as x(
       id text, name text, search_text text, courses jsonb,
       identity_profile_url text, identity_evidence_url text
     )
where x.id = identity.professor_id
on conflict (person_id) do update set updated_at = now();

update professor_courses course
set instructor_person_id = identity.person_id
from professor_staff_identities identity
where identity.professor_id = course.professor_id;

insert into course_enrollments (
  academic_year, term, course_code, class_code, class_nbr, component,
  section, quota, vacancy, instructors, captured_at
)
select x.academic_year, x.term, x.course_code, x.class_code, x.class_nbr,
       x.component, x.section, x.quota, x.vacancy,
       array(select jsonb_array_elements_text(x.instructors)), meta.captured_at
from _professor_import,
     lateral (select (payload->>'captured_at')::timestamptz captured_at) meta,
     jsonb_to_recordset(payload->'enrollments') as x(
       academic_year text, term text, course_code text, class_code text,
       class_nbr text, component text, section text, quota integer,
       vacancy integer, instructors jsonb
     );

with unique_aliases as (
  select alias, min(person_id) person_id
  from staff_aliases
  group by alias
  having count(distinct person_id) = 1
)
insert into course_offering_instructors (
  academic_year, term, course_code, class_code, component, section,
  instructor_name, person_id, match_status, evidence_url, captured_at
)
select enrollment.academic_year, enrollment.term, enrollment.course_code,
       enrollment.class_code, enrollment.component, enrollment.section,
       instructor.name, alias.person_id,
       case
         when person.identity_kind = 'external' then 'external'
         when alias.person_id is not null then 'automatic'
         else 'unverified'
       end,
       person.profile_url, enrollment.captured_at
from course_enrollments enrollment
cross join lateral unnest(enrollment.instructors) instructor(name)
left join unique_aliases alias on alias.alias = instructor.name
left join staff_people person on person.id = alias.person_id
on conflict do nothing;

update course_offering_instructors offering
set person_id = person.id,
    match_status = 'manual',
    evidence_url = override.evidence_url
from _professor_import,
     jsonb_to_recordset(payload->'overrides') as override(
       course_prefix text, instructor_name text, profile_url text,
       evidence_url text
     )
join staff_people person on person.profile_url = override.profile_url
where offering.instructor_name = override.instructor_name
  and offering.course_code like override.course_prefix || '%';

delete from staff_teaching_assignments;
insert into staff_teaching_assignments (
  person_id, academic_year, term, course_code, captured_at
)
select distinct offering.person_id, offering.academic_year,
       case when offering.term = 'Summer Session' then 'Summer'
            else offering.term end,
       offering.course_code, offering.captured_at
from course_offering_instructors offering
where offering.person_id is not null
on conflict do nothing;

delete from professors professor
where not exists (
    select 1 from professor_courses course
    where course.professor_id = professor.id
  )
  and not exists (
    select 1 from course_reviews review
    where review.professor_id = professor.id
  )
  and not exists (
    select 1 from course_ratings rating
    where rating.professor_id = professor.id
  );

commit;
`;
}

async function main() {
  const source = JSON.parse(
    await readFile(resolve("scripts/data/professors.json"), "utf8"),
  ) as {
    capturedAt: string;
    professors: Array<TeachingStaffSource & { id?: string }>;
    enrollments: Enrollment[];
  };
  const overrides = JSON.parse(
    await readFile(resolve("scripts/course-instructor-overrides.json"), "utf8"),
  ) as CourseInstructorOverride[];
  const catalog = buildProfessorCatalog(source.professors, overrides);
  const payload = {
    captured_at: source.capturedAt,
    professors: catalog.map((record) => ({
      id: record.id,
      name: record.name,
      search_text: record.searchText,
      courses: record.courses,
      identity_profile_url: record.identityProfileUrl ?? null,
      identity_evidence_url: record.identityEvidenceUrl ?? null,
    })),
    enrollments: source.enrollments.map((row) => ({
      academic_year: row.academicYear,
      term: row.term,
      course_code: row.courseCode,
      class_code: row.classCode,
      class_nbr: row.classNbr,
      component: row.component,
      section: row.section,
      quota: row.quota,
      vacancy: row.vacancy,
      instructors: row.instructors
        .map(normalizeProfessorName)
        .filter(isValidProfessorName),
    })),
    overrides: overrides.map((override) => ({
      course_prefix: override.coursePrefix,
      instructor_name: normalizeProfessorName(override.instructorName),
      profile_url: override.profileUrl,
      evidence_url: override.evidenceUrl,
    })),
  };
  const output = resolve("scripts/data/professor-import.sql");
  await writeFile(output, renderProfessorImportSql(payload), "utf8");
  console.log(
    `Rendered ${catalog.length} professors and ${source.enrollments.length} enrollments -> ${output}`,
  );
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
